### ISSUE TITLE
provide source RPM file

### ISSUE THREAD

**Issue by alaniwi** [Prodiguer/synda#102]
CEDA is interested in having RPM releases of recent versions of synda.

If you can please provide the source RPM (`synda_<version>.src.rpm`) which was used to create the existing binary RPM versions which are visible at http://sd-104052.dedibox.fr/synda/sdt/rpm/, then perhaps we can help to produce updated RPMs for later versions of synda (at least, to produce an updated source RPM and also updated binary RPMs for those platforms to which we have access).

This source RPM must exist somewhere, because the binary RPMs could not have been produced without it -- or at least, the RPM spec file must have existed, because to build the binary RPMs requires running the command `rpmbuild -bb <spec_file>`. Similarly the source RPM can be built using `rpmbuild -bs <spec_file>`. (Both of these commands assume that the sources referenced in the spec file exist in a `SOURCES` directory parallel to the directory containing the spec file.)  It would be equivalently useful to provide instead the RPM spec file itself, on condition that it does not reference any source files which are not available from the website (for example, any patches).

Thank you.

**Comment by AtefBN** [comment]
Hi @alaniwi I think we will be in the future distributing Synda via conda package only and therefore will not be giving support to RPM packaging.
