### ISSUE TITLE
Synda support for python3

### ISSUE THREAD

**Issue by durack1** [Prodiguer/synda#111]
Hi folks, I've just installed the synda v3.9 rpm on a RHEL6.10 machine. I was following the guidance at http://prodiguer.github.io/synda/sdp/rpm_install.html - with rpm updates
```
yum install http://sd-104052.dedibox.fr/synda/sdt/rpm/synda-3.9-1.x86_64_centos67.rpm
```

It seems that when I try an follow the 3.8 bugfix note (https://github.com/Prodiguer/synda/blob/master/sdt/doc/rpm_install.md), however it seems that I'm hitting errors with python2.6

```
[~]$ sudo /usr/share/python/synda/sdt/bin/pip install --trusted-host pypi.python.org myproxyclient==2.1.0
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Collecting myproxyclient==2.1.0
/usr/share/python/synda/sdt/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
...
```

Is there a python3 supported version of Synda that can be installed so such issues don't occur?

**Comment by painter1** [comment]
I use /usr/share/python/synda/sdt/bin/python2.7

**Comment by durack1** [comment]
@painter1 thanks, did you install using the rpms, or did you undertake an install from source? (I'm guessing the latter)

**Comment by durack1** [comment]
@AtefBN @glevava ping!

**Comment by painter1** [comment]
Cameron Harr did the installs.  So I don't know, but it was very probably from rpms.

**Comment by cmharr** [comment]
I used rpms for scientific Linux

Sent from my iPhone

On May 9, 2019, at 11:45 AM, Jeffrey Painter <notifications@github.com<mailto:notifications@github.com>> wrote:


Cameron Harr did the installs. So I don't know, but it was very probably from rpms.

**Comment by AtefBN** [comment]
@durack1 Hi Paul, yes there's an issue with the myproxyclient dependency if you're running on python 2.6 and the release currently I'm working on is 2.7 exclusively. I'm choosing to go to 2.7 for now in preparation for the synda release on python 3.

**Comment by durack1** [comment]
@AtefBN sounds great, let me know when you expect a new release and I'll give it a go.

Also wondering is a conda release is likely, that might reduce the overhead of *.rpm building for you guys a little?

**Comment by AtefBN** [comment]
@durack1 Very soon. Currently working out a few bugs. I'll let you guys know when it's live and you'll be my testers :+1: 
For the time being the release i'm working on is via PIP. Conda is not out of question but I think packaging via pypi should be enough since there shouldn't be conflicting dependencies and at worst it could be installed within virtualenv.

**Comment by durack1** [comment]
@AtefBN sounds great! FYI, we're always a good test case as the security imposed at LLNL means certificate issues etc are an ongoing challenge, and pip distributions often just don't work. We've managed to standardize on conda for most of the packages here (e.g. https://anaconda.org/CDAT, https://anaconda.org/PCMDI/), which has worked great, and enable relatively nimble installation across a large array of linux and python2/3 environment variants.

@dnadeau4 @doutriaux1 and others here should be available to provide some conda recipe examples if you wanted to fast-track such a release

**Comment by AtefBN** [comment]
Unfortunately not yet. But I'm working full time on it currently (well as soon as I get back in office) so it shouldn't really take long for a beta version to be out.

**Comment by pjournou-ipsl** [comment]
Synda works with python 3 from March'21
