### ISSUE TITLE
Daemon fails silently without issuing an error message

### ISSUE THREAD

**Issue by ghost** [Prodiguer/synda#12]
When the daemon fails to start, an error message should be printed to inform user

**Comment by jgs900** [comment]
You should find a stack trace is dumped to /tmp/sdt_stacktrace_*

Still not ideal though

**Comment by AtefBN** [comment]
A bit tricky to implement, the daemon no longer has access to stdout as soon as the daemon context is created by Synda and it communicates via transfer.log exclusively. Doing any different would compromise the benefit itself of using a daemon. 
I have in the current conda release though added a compromise, in the form of a message that synda sends right before giving the reins to the daemon. At that point if anything wrong happens with the launch of the daemon, it should be visible in transfer.log. 
I'll be therefore marking this issue as closed, but if you have a different opinion feel free to re-open and i'm all ears :)
