### ISSUE TITLE
Command 'facet' does not know about CMIP6 facets

### ISSUE THREAD

**Issue by senesis** [Prodiguer/synda#120]
A number of CMIP6 facets such as "experiment_id" (see [complete list](https://docs.google.com/document/d/1h0r8RZr_f3-8egBMMh7aqLwy3snpD6_MrDz1q8n5XUk/edit) are not known to sub-command facet : 

`# synda facet experiment_id  | column`
`Unknown facet`

**Comment by AtefBN** [comment]
Hello @senesis I ran two seperate tests on synda 3.9 and synda 3.10 and cannot replicate the behavior :
![facet](https://user-images.githubusercontent.com/15193639/63024614-d9899880-bea7-11e9-8660-544f923cbeb3.png)

Can you provide me with more details about the issue (relevant log file) or can you test if installing the 3.10 synda package still has the same misbehavior ? Thanks.

**Comment by senesis** [comment]
I cannot upgrade to 3.10 (using DEB package)
Re_installing 3.9 again rises issue #119 ; I did put a workaround in my previous install, but would prefer to have a clean solution before reproducing the error on CMIP6 facets

**Comment by AtefBN** [comment]
3.10 comes in a conda package with a smooth install process and should be able to support upgrade from DEB package as long as the local files are migrated properly. Future releases will almost certainly be conda exclusive as it provides a balance between all synda uses. 
(I can provide a step by step walkthrough for this.)

**Comment by senesis** [comment]
So, I assume that I also have to match the file locations described for [DEB install ](http://prodiguer.github.io/synda/sdt/deb_install.html#files-location)to [those listed in source install](http://prodiguer.github.io/synda/sdt/src_install.html#files-location). Do I ?

**Comment by senesis** [comment]
In which ST_HOME subdir should the content of /etc/synda/sdt/default be copied ? 
Same question for /etc/synda/sdt/selection

**Comment by senesis** [comment]
And now , here I am :

`(py27) stephane@pavilion-stephane:~$ synda facet experiment_id | column`
`Unknown facet`
`(py27) stephane@pavilion-stephane:~$ synda --version`
`3.10`

Is there a config file (describing facets) which could be different in your case and mine ?
Note : there is nothing relevant in the logfiles

**Comment by AtefBN** [comment]
Sorry for the delay I was doing a quick write up on the conda install procedure (for future reference : http://prodiguer.github.io/synda/sdt/conda_install.html# ) 
Okay, the error leads me to think the issue lays within the db cache. Would you please bear with me, copy your synda files elsewhere (or simply change ST_HOME variable) and run the same command on a from scratch synda file environment.
You can init a new environment by running synda check-env.

**Comment by senesis** [comment]
I used `synda init-env` with a new ST_HOME, and that worked OK for `synda facet ...`. Thanks a lot

Two remarks :
- in your new doc paragraph dealing with conda install, you need to describe/define ST_HOME
- when using a conda install , the user should not use `sudo` because this may drive him to use another install; so, you should recall the need to belong to the synda group

Thanks again

**Comment by AtefBN** [comment]
So the issue is basically in the old db structure. There were some slight modifications in this release (added a table and a column to support a PR provided by Jeff Painter). 
Duly noted! :D 
I did copy paste ST_HOME tree command result but when generating the html via sphinx, it didn't like them and shrugged them off. I'll simply include a static png and redeploy. 
And I will definitely make sure to specify the details of users affiliations too. 
Thank you Stephane for the help !
