### ISSUE TITLE
data transfer bottleneck fix

### ISSUE THREAD

**Issue by painter1** [Prodiguer/synda#122]
I noticed that, when trying to get over 60 simultaneous file transfers, Synda's performance becomes a bottleneck limiting data throughput.  At LLNL I have made three changes which eliminated the problem for the moment.  One is a simple database change, described below.  The others are small coding changes which I will submit as pull requests once my existing pull requests are dealt with.

The database problem arises through sddao.get_one_waiting_transfer().  It initiates a search for a data_node in the file table.  With a 4 GB database, this usually requires over two seconds per search.  We need another index in the database, on data_node.  Add ing the index reduces the time to well under a half second per search:
sqlite> CREATE INDEX idx_file_13 ON file (data_node);

**Comment by AtefBN** [comment]
I think there's no harm in adding this to the db schema and only benefits to reap. 
I'll add the index to the db. And it should be in the next release. I will close the issue when it's live.
