### ISSUE TITLE
Synda search obs4MIPs error

### ISSUE THREAD

**Issue by hot007** [Prodiguer/synda#131]
I also found that in the conda install of Synda 3.10 (on a centOS7 VM) fails with obs4MIPs.

`> synda search obs4MIPs

*** Error occured at 2020-02-11 00:18:04.995314 ***

Traceback (most recent call last):
  File "/home/---/.conda/envs/synda-env/bin/synda", line 11, in <module>
    sys.exit(run())
  File "/home/---/.conda/envs/synda-env/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/synda.py", line 167, in run
    status=sdtsaction.actions[args.subcommand](args)
  File "/home/---/.conda/envs/synda-env/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdtsaction.py", line 85, in search
    dataset_search(args)
  File "/home/---/.conda/envs/synda-env/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdtsaction.py", line 210, in dataset_search
    datasets=sdrdataset.get_datasets(stream=args.stream,dry_run=args.dry_run)
  File "/home/---/.conda/envs/synda-env/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdrdataset.py", line 38, in get_datasets
    result=sdquicksearch.run(stream=stream,parameter=parameter,post_pipeline_mode=post_pipeline_mode,dry_run=dry_run)
  File "/home/---/.conda/envs/synda-env/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdquicksearch.py", line 77, in run
    mqr=process_queries(queries)
  File "/home/---/.conda/envs/synda-env/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdquicksearch.py", line 93, in process_queries
    mqr.slurp(ws_call(query))
  File "/home/---/.conda/envs/synda-env/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdquicksearch.py", line 99, in ws_call
    result=sdnetutils.call_web_service(request.get_url(),timeout=sdconst.SEARCH_API_HTTP_TIMEOUT) # return Response object
  File "/home/---/.conda/envs/synda-env/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdnetutils.py", line 74, in call_web_service
    return sdtypes.Response(call_duration=elapsed_time,lowmem=lowmem,**di) # RAM storage is ok here as one response is limited by SEARCH_API_CHUNKSIZE
  File "/home/---/.conda/envs/synda-env/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdtypes.py", line 444, in __init__
    CommonIO.__init__(self,*args,**kwargs)                         # call base class initializer
  File "/home/---/.conda/envs/synda-env/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdtypes.py", line 318, in __init__
    self.size=compute_total_size(files)
  File "/home/---/.conda/envs/synda-env/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdtypes.py", line 377, in compute_total_size
    return sum(int(f['size']) for f in files)
  File "/home/---/.conda/envs/synda-env/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdtypes.py", line 377, in <genexpr>
    return sum(int(f['size']) for f in files)
KeyError: 'size'`

**Comment by AtefBN** [comment]
Ouch, yes I could replicate this error on my machine. I'll need a bit of time to investigate and deploy a fix but I'm on it.

**Comment by AtefBN** [comment]
After quick dig up I found that the reason for this error is a bad publication probably, as synda receives the list of files expected to be returned and attempts to compute the total size. Except while synda expect a dictionary such as this : 
`{u'data_node': u'aims3.llnl.gov', u'instance_id': u'obs4MIPs.RSS.RSS-v7.mon.sfcWind.gn.v20180305', u'score': 1.0, u'variable': [u'latitude_bounds', u'longitude_bounds', u'sfcWind', u'time_bounds'], u'type': u'Dataset', u'id': u'obs4MIPs.RSS.RSS-v7.mon.sfcWind.gn.v20180305|aims3.llnl.gov', u'size': 348474384}
`
There's one element of the list returned that is rogue: 
`|{u'variable': [u'pr', u'ranEr'], u'score': 1.0, u'type': u'Dataset', u'id': u'obs4MIPs.NASA-GSFC.GPM.atmos.mon.v20191030|esgf.nccs.nasa.gov', u'data_node': u'gpm1.gesdisc.eosdis.nasa.gov'}
`
My experience in publication of obs4MIPS data is non-existent so I can only assume this was a mistake, however Synda should be resilient to this kinda of behavior from the stack. 
For some reason I can't seem to get conda to build a new release. But to get things back in working order for you just copy paste the contents of sdremoveaggregation and sdtypes from this repo into your local install paths (ie "/home/---/.conda/envs/synda-env/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdtypes.py") I'll ping here when a new release is up! and sorry for the inconvenience.

**Comment by hot007** [comment]
Hmm, moved the error anyway.. ;-)
Last line of trace is now

```
  File "/home/---/.conda/envs/synda-env/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdtypes.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```

**Comment by AtefBN** [comment]
Hmm this is strange, from my fresh install I get the proper response: 
`synda search obs4MIPS
[{'protocol': 'http', 'fields': ['instance_id,id,variable,data_node,type,size'], 'selection_filename': 'cli', 'limit': ['6000'], u'project': [u'obs4MIPs'], 'selection_file': 'cli', 'local_path_format': 'tree', 'distrib': ['true'], 'progress': True, 'type': ['Dataset'], 'action': 'search'}]
Request sent to esgf-data.dkrz.de. Please wait..
Search completed.                                                                                   

new  obs4MIPs.NCEI.OISST.tos.mon.v20160401
new  obs4MIPs.NCEI.OISST.tos.day.v20160401
new  obs4MIPs.NCEI.OLR.rlut.mon.v20160401
new  obs4MIPs.NCEI.OLR.rlut.day.v20160401
new  obs4MIPs.NCEI.PMSIC.SH.sic.day.v20160401
new  obs4MIPs.NCEI.PMSIC.NH.sic.day.v20160401
new  obs4MIPs.NCEI.PMSIC.SH.sic.mon.v20160401
new  obs4MIPs.NCEI.PMSIC.NH.sic.mon.v20160401
new  obs4mips.SU.ATSR2-AATSR.od550aer.mon.v20160922
new  obs4MIPs.FUB-DWD.SSMI-MERIS.prw.mon.v20140616
new  obs4MIPs.UOE.ARC-SST-1-1.mon.v1
new  obs4MIPs.IPSL.CALIPSO.uncalipso.night.v20110323
new  obs4MIPs.IPSL.CALIPSO.uncalipso.day.v20110323
new  obs4MIPs.IPSL.CALIPSO.uncalipso.mon.v20110323
new  obs4MIPs.LOA-IPSL.PARASOL.parasolRefl.day.v20110323
new  obs4MIPs.LOA-IPSL.PARASOL.parasolRefl.mon.v20110323
new  obs4MIPs.LOA-IPSL.PARASOL.sza.day.v20110323
new  obs4MIPs.LOA-IPSL.PARASOL.sza.mon.v20110323
new  obs4MIPs.UW.MISR.clMISR.mon.v20131113
new  obs4MIPs.UW.MISR.samplesMISR.mon.v20131113
new  obs4MIPs.IPSL.CALIPSO.clhcalipso.night.v20110323
new  obs4MIPs.IPSL.CALIPSO.cllcalipso.night.v20110323
new  obs4MIPs.IPSL.CALIPSO.clhcalipso.day.v20110323
new  obs4MIPs.IPSL.CALIPSO.clhcalipso.mon.v20110323
new  obs4MIPs.IPSL.CALIPSO.cllcalipso.day.v20110323
new  obs4MIPs.IPSL.CALIPSO.cllcalipso.mon.v20110323
new  obs4MIPs.IPSL.CALIPSO.clccalipso.night.v20110323
new  obs4MIPs.IPSL.CALIPSO.clccalipso.day.v20110323
new  obs4MIPs.IPSL.CALIPSO.clccalipso.mon.v20110323
new  obs4MIPs.PCMDI.CloudSat.missingdatafraction.mon.v20130503
new  obs4MIPs.PCMDI.ISCCP.clisccp.mon.v20130503
new  obs4MIPs.PCMDI.CloudSat.cfadDbze94.mon.v20130503
new  obs4MIPs.PCMDI.ISCCP.albisccp.mon.v20130503
new  obs4MIPs.PCMDI.CloudSat.overpasses.mon.v20130503
new  obs4MIPs.PCMDI.CloudSat.cltcloudsat.mon.v20130503
new  obs4MIPs.IPSL.CALIPSO.cfad2Lidarsr532.night.v20110323
new  obs4MIPs.IPSL.CALIPSO.cfadLidarsr532.night.v20110323
new  obs4MIPs.IPSL.CALIPSO.cfad2Lidarsr532.day.v20110323
new  obs4MIPs.IPSL.CALIPSO.cfad2Lidarsr532.mon.v20110323
new  obs4MIPs.IPSL.CALIPSO.clcalipso.night.v20110323
new  obs4MIPs.IPSL.CALIPSO.cfadLidarsr532.day.v20110323
new  obs4MIPs.IPSL.CALIPSO.cfadLidarsr532.mon.v20110323
new  obs4MIPs.IPSL.CALIPSO.clcalipso.day.v20110323
new  obs4MIPs.IPSL.CALIPSO.clcalipso.mon.v20110323
new  obs4MIPs.PCMDI.ISCCP.cltisccp.mon.v20130503
new  obs4MIPs.IPSL.CALIPSO.clrcalipso.night.v20110323
new  obs4MIPs.IPSL.CALIPSO.clrcalipso.day.v20110323
new  obs4MIPs.IPSL.CALIPSO.clrcalipso.mon.v20110323
new  obs4MIPs.IPSL.CALIPSO.clmcalipso.night.v20110323
new  obs4MIPs.IPSL.CALIPSO.clmcalipso.day.v20110323
new  obs4MIPs.IPSL.CALIPSO.clmcalipso.mon.v20110323
new  obs4MIPs.IPSL.CALIPSO.cltcalipso.night.v20110323
new  obs4MIPs.IPSL.CALIPSO.cltcalipso.day.v20110323
new  obs4MIPs.IPSL.CALIPSO.cltcalipso.mon.v20110323
new  obs4MIPs.PCMDI.ISCCP.cttisccp.mon.v20130503
new  obs4MIPs.PCMDI.ISCCP.pctisccp.mon.v20130503
new  obs4MIPs.NASA-LaRC.CERES-EBAF_Surface.atmos.mon.v20160610
new  obs4MIPs.NASA-GSFC.MODIS.atmos.mon.v20160614
new  obs4MIPs.NASA-LaRC.CERES-EBAF.atmos.mon.v20160610
new  obs4MIPs.ECMWF.ERA-interim.atmos.mon.v20160614
new  obs4MIPs.NASA-GSFC.TRMM.atmos.mon.v20160613
new  obs4MIPs.NASA-GSFC.MODIS.land.mon.v20160614
new  obs4MIPs.NASA-GSFC.TRMM.atmos.3hr.v20160613
new  obs4MIPs.NASA-GSFC.MISR.atmos.mon.v20160614
new  obs4MIPs.NASA-GSFC.GPCP-V1.3.atmos.day.v20180519
new  obs4MIPs.NASA-GSFC.GPCP-V2.2.atmos.mon.v20180518
new  obs4MIPs.NASA-GSFC.GPCP-V1.2.atmos.day.v20180518
new  obs4MIPs.NASA-GSFC.GPCP-V2.3.atmos.mon.v20180519
new  obs4MIPs.NASA-GSFC.AIRS.atmos.mon.v20200206
new  obs4MIPs.NASA-GSFC.GPM.atmos.mon.v20200211
new  obs4MIPs.NASA-GSFC.MODIS-1-0.mon.clt.gn.v20180305
new  obs4MIPs.NASA-JPL.AIRS-1-0.mon.hus.gn.v20110608
new  obs4MIPs.NASA-JPL.AIRS-1-0.mon.ta.gn.v20110608
new  obs4MIPs.NASA-JPL.AIRS-2-0.mon.hur.gn.v20180307
new  obs4MIPs.CNES.AVISO-1-0.mon.zos.gn.v20180305
new  obs4MIPs.NASA-JPL.GNSS-RO-1-3.mon.zg.gn.v20160601
new  obs4MIPs.NASA-JPL.GNSS-RO-1-3.mon.ta.gn.v20160601
new  obs4MIPs.NASA-JPL.Aura-MLS-v04-2.mon.cli.gn.v20160504
new  obs4MIPs.NASA-JPL.Aura-MLS-v04-2.mon.hus.gn.v20111025
new  obs4MIPs.NASA-JPL.Aura-MLS-v04-2.mon.ta.gn.v20111025
new  obs4MIPs.NASA-JPL.QuikSCAT-v20110531.mon.sfcWind.gn.v20120411
new  obs4MIPs.NASA-JPL.QuikSCAT-v20110531.mon.uas.gn.v20120411
new  obs4MIPs.NASA-JPL.AIRS-2-0.mon.hus.gn.v20180307
new  obs4MIPs.NASA-JPL.AIRS-2-0.mon.ta.gn.v20180307
new  obs4MIPs.RSS.RSS-v7.mon.prw.gn.v20180305
new  obs4MIPs.RSS.RSS-v7.mon.tos.gn.v20180305
new  obs4MIPs.RSS.RSS-v7.mon.sfcWind.gn.v20180305
new  obs4MIPs.NASA-JPL.QuikSCAT-v20110531.mon.vas.gn.v20120411
new  obs4MIPs.NASA-JPL.TES-1-0.mon.tro3.gn.v20110608
`
Btw this new version is now up in conda so could you run : 
`conda upgrade synda`
And tell me if this behavior persists ? Thanks!

**Comment by hot007** [comment]
oh I'm silly, I didn't wget the right thing, I got the html not the contents of the files!! all good, works as expected now, thank you! This one can be closed then I think.

**Comment by AtefBN** [comment]
Great! Glad it helped.
