### ISSUE TITLE
Lastest version, documentation and CMIP6 support

### ISSUE THREAD

**Issue by YanchunHe** [Prodiguer/synda#134]
Hi,

Thank you for developing this great tool!  However, I find the lastest release v3.10 from conda seems lack support to many CMIP6 data search/download. And the documentation to install and use this tool is somehow outdated.  Are you going to have a latest release and update the documentation? Thanks!
(Sorry if here is not the right place to ask about this).

Yanchun

**Comment by AtefBN** [comment]
Hello Yanchun,

Yes the development of synda is still ongoing, the version 3.10 was sort of a hasty release to answer few urgent issues that were encountered by users. Feel free to create specific issues in here about the specific use cases where synda didn't act as expected, this will help me replicate issues and subsequently solve them and provide a patch release. 

Main current development cycle is focused on bringing synda to python 3.7 instead of 2.7 and I'm seizing the opportunity to refactor some parts that didn't age well. 
Hope this answers your question. 

Atef.

**Comment by YanchunHe** [comment]
Hi Atef,

Thanks a lot for your prompt response!  I understand the situation that you and the colleagues are busy with the development.

First of all, the documentation is for v3.0 if understand correctly, [syda documentation](http://prodiguer.github.io/synda/), and I sometimes find it hard to digest what does some of it means and how to invoke the parameters. (but maybe this is not of high priority now)

Second, I find synda can not find and download quite some latest CMIP6 model data.
For example:
```
$ synda facet model
``
The NorESM2-LM and NorESM2-MM models for CMIP6 are not listed, but only only NorESM1-M
NorESM1-ME for CMIP5.

However, `synda search NorESM2-LM` does give some results (but very few):
```
$ synda search NorESM2-LM
new  CMIP6.PAMIP.NCC.NorESM2-LM.pdSST-pdSIC.r46i1p1f1.AERmon.mmroa.gn.v20190920
new  CMIP6.PAMIP.NCC.NorESM2-LM.pdSST-pdSIC.r46i1p1f1.Amon.hus.gn.v20190920
...
new  CMIP6.PAMIP.NCC.NorESM2-LM.pdSST-pdSIC.r50i1p1f1.Amon.ps.gn.v20190920
```

But
```
$ synda search model=NorESM2-LM
Dataset not found
```

And what is the difference of the output by `synda facet` and `synda param`, for example:
```
$ synda param cmor_table
3hr
6hrLev
6hrPlev
Amon
LImon
Lmon
OImon
Omon
Oyr
aero
day
fx
```

while  `synda facet cmor_table` gives quite different results, and quite some of these 'tables' are not CMIP6 tables.
```
$ synda facet cmor_table
3hr
3hrCurt
3hrMlev
3hrPlev
3hrSlev
6hr
6hrLev
6hrPlev
6hrPlevPt
A3hr
AERmon
Aclim
Aday
Amon
AmonExtras
CFday
CFmon
Emon
LIclim
LImon
Lclim
Lmon
OIclim
OImon
Oclim
Oday
Omon
OmonExtras
Oyr
OyrExtras
Prim6hr
Prim6hrPt
PrimOday
PrimOmon
Primday
PrimdayPt
SIday
SImon
aero
cf3hr
cfDay
cfMon
cfOff
cfSites
day
dayExtras
fx
sites
```

These are something quite confusing to me. Sorry I did something stupid here...

Best,
Yanchun

**Comment by YanchunHe** [comment]
forget to mention, I have run `synda update`, to update my local cache.

**Comment by AtefBN** [comment]
Quite a few questions there, I'll try to answer to the best of my ability: 

regarding the difference between setting Model = and not setting it when searching is due to an old feature in Synda that we have been considering getting rid of for this exact reason, it confuses more than helps people. Synda uses inference to try to help users by interpreting their input however that inference algorithm is not deterministic and has varying results. 

In this case it worked when you didn't specify that NorESM2-LM model is the facet you're looking for but not when you specifically assigned the facet value to it. 
Regarding the number of results. This depends heavily on which index node you're targeting by using synda which is configured in synda configuration file by order of priority. Playing with the index node values will yield different results. 

I agree that the model doesn't exist in the db I could replicate this on our test node.  I'll look into it. 
Synda param simply prints the facets within the db, synda facet is supposed to fetch them from ESGF, (which also depends on the node you're hitting). After an update they should yield the same results. I'll look into as well asap. 

PS: Feel free to create separate issues for each problem you have, this will help me keep track of the exact number of ongoing issues and help me and you track the progress of resolution. 
@glevava Could provide further insight into the issues discussed here as he spent far more time than I have with the tool.

**Comment by YanchunHe** [comment]
Thanks a lot, Atef. You replies answer or at least confirm quite some of questions/issues. (indeed, index_node, data_node are something I forget to mention above).

I will try to create specific issues shortly to make it easier to keep track of..
Really appreciate your help!

Yanchun

**Comment by glevava** [comment]
Hi @YanchunHe I can provide details here on the synda behavior and maybe your misusage:

> I sometimes find it hard to digest what does some of it means and how to invoke the parameters. 

Once synda 3.0 is released we already plan to review the documentation accordingly. But we have to manage and focus our effort to avoid doing things twice.

> synda search NorESM2-LM does give some results (but very few):

By default synda only prints 100 items among the results. This can be change with the `-l` option. See the command-line documentation:
```
  -l LIMIT, --limit LIMIT
                        Set the total number of returned results. By default,
                        returns the first 100 records matching the given
                        constraints. Limit can be also be changed through the
                        keyword parameters limit=. The system imposes a
                        maximum value of limit <= 10,000.
```
> $ synda search model=NorESM2-LM

the "model" facet doesn't exist un CMIP6. You should query `synda search source_id=NorESM2-LM` which actually returns the same result as `synda search NorESM2-LM`.

> the difference of the output by synda facet and synda param

`synda param` only quieries the database on which synda relies. So it will basically "list" the facet value you have in your cache. If some values are missing in comparison of ESGF portal, the `synda update` will update the cache fetching new facet values from the ESGF.
Did you update you cache before or after the `synda param` command? On my side `synda param cmor_table` returns much more results.

`synda facet` quieries the index node (not the database) and return the existing values of the submit facet key. The results depend on the published data on the ESGF. This is not the exhaustive list of possible facet values. It's expected that `synda update` + `synda param key` = `synda facet key` for a given facet key.

I also warn you that `cmor_table` doesn't exist as CMIP6 key. This is `table_id` instead.

**Comment by glevava** [comment]
From my point of view, there are no issues to create.

**Comment by YanchunHe** [comment]
Hi @glevava , thanks a lot for your reply. It answers most of my questions. 

There are then one other issue (not sure if it is also a simple misgauge problem).

for example,

first i update my local cache, and search a dataset
```
$ synda update -i esgf-data.dkrz.de
$ synda search source_id=NorESM2-MM experiment_id=historical table_id=Omon variable_id=tos
CMIP6.CMIP.NCC.NorESM2-MM.historical.r1i1p1f1.Omon.tos.gn.v20191108
```

then if I try to download this data by:
```
$ synda get -d /projects/NS9252K/raw/ CMIP6.CMIP.NCC.NorESM2-MM.historical.r1i1p1f1.Omon.tos.gn.v20191108
```
it gives error:
```
  File "/projects/NS9252K/conda/synda/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdglobus.py", line 29, in <module>
    import globus_sdk
ImportError: No module named globus_sdk
```
This issue can be solved by
```
conda install globus-sdk
```

However, if I try to download again, it gives further error:
```
File "/projects/NS9252K/conda/synda/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdglobus.py", line 115, in <module>
    dst_directory = sdconfig.config.get("globustransfer", "destination_directory")
  File "/projects/NS9252K/conda/synda/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'destination_directory' in section: 'globustransfer'
```

But I have set the dest_directory by the `-d` option.

in `sdt.conf`, I also set:
```
data_path = /projects/NS9252K/raw
```

Thanks!

Yanchun

**Comment by glevava** [comment]
@YanchunHe 
At the end of the `sdt.conf` you should find a section called `[globustransfer]`. You add `destination_directory=/projects/NS9252K/raw` into and try again.

**Comment by YanchunHe** [comment]
Thanks @glevava !

Indeed, this fix the problem. But, I found I have add both `destination_directory` and `destination_endpoint`, otherwise, the program will complain either of them is not set.

There is finally a credential/authentication problem with the myproxy setting, or with may be with ssl.

I have set up `~/.synda/conf/credentials.conf` as:
```
[esgf_credential]
openid = https://esgf-data.dkrz.de/esgf-idp/openid/myusername
password = xxxx(my pass)
```

But there is some error with my proxy/ssl:
```
*** Error occured at 2020-03-30 15:54:32.667925 ***

Traceback (most recent call last):
  File "/projects/NS9252K/conda/synda/bin/synda", line 11, in <module>
    sys.exit(run())
  File "/projects/NS9252K/conda/synda/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/synda.py", line 178, in run
    status=sdtiaction.actions[args.subcommand](args)
  File "/projects/NS9252K/conda/synda/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdtiaction.py", line 244, in get
    sdlogon.renew_certificate(oid,pwd,force_renew_certificate=False)
  File "/projects/NS9252K/conda/synda/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdlogon.py", line 78, in renew_certificate
    sdmyproxy.run(hostname,port,username,force_renew_certificate,force_renew_ca_certificates,password)
  File "/projects/NS9252K/conda/synda/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdmyproxy.py", line 76, in run
    renew_certificate(host,port,username,password)
  File "/projects/NS9252K/conda/synda/lib/python2.7/site-packages/synda-3.10-py2.7.egg-info/scripts/sdmyproxy.py", line 155, in renew_certificate
    authnGetTrustRootsCall=authnGetTrustRootsCall)
  File "/projects/NS9252K/conda/synda/lib/python2.7/site-packages/myproxy/client/__init__.py", line 1455, in logon
    **getTrustRootsKw)
  File "/projects/NS9252K/conda/synda/lib/python2.7/site-packages/myproxy/client/__init__.py", line 1624, in getTrustRoots
    dat += conn.recv(self.SERVER_RESP_BLK_SIZE)
  File "/projects/NS9252K/conda/synda/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1809, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/projects/NS9252K/conda/synda/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1671, in _raise_ssl_error
    _raise_current_error()
  File "/projects/NS9252K/conda/synda/lib/python2.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
Error: [('SSL routines', 'ssl3_read_n', 'unexpected eof while reading')]
```

If I directly use `myproxyclient`:
```
$ myproxyclient logon -s esgf-data.dkrz.de  -l yanchunhe -o creds.pem -b
Enter password for user 'yanchunhe' on MyProxy server 'esgf-data.dkrz.de':
Error retrieving credentials: [('SSL routines', 'ssl3_read_n', 'unexpected eof while reading')]
```

Wondering this belongs to the scope of the `synda`, if not, I will try to find solutions somewhere else. Anyway, thanks for the help!

Yanchun

**Comment by glevava** [comment]
Hi @YanchunHe actually this is an ssl issue, not related to synda. synda use the same myproxyclient command line to retrieve ESGF certificates.

**Comment by YanchunHe** [comment]
Yes, I think so too. I will try to fix that. Thanks a lot @glevava !
