### ISSUE TITLE
Unexpected eof while retrieving certificate 

### ISSUE THREAD

**Issue by Fehings** [Prodiguer/synda#138]
Hi,
Firstly thank you for making this great tool! I am just running into an issue trying to get the downloads working.
I have been able to search fine, but when attempting to retrieve data I have found the daemon fails to start.
I run `synda install sample_selection_01.txt` (for example, have tried others) this retrieves files for download and prompts me to start the daemon. Running `synda daemon start` then doesn't give any errors, but then `synda daemon` returns `daemon not running`.
Checking the log file shows the error:
```
Daemon successfully started
2020-04-01 08:23:24,407 INFO SDDAEMON-001 Daemon starting ...
INFO: Connected to /home/lo99/.synda/db/sdt.db
2020-04-01 08:23:24,408 INFO SDTSCHED-533 Connected to /home/lo99/.synda/db/sdt.db
2020-04-01 08:23:24,408 INFO SDTSCHED-993 Starting watchdog..
2020-04-01 08:23:25,269 INFO SDMYPROX-002 Renew certificate..
2020-04-01 08:23:27,856 ERROR SYDLOGON-012 Error occured while retrieving certificate from myproxy server ([('SSL routines', 'ssl3_read_n', 'unexpected eof while reading')])
Daemon successfully started
```
When then running `synda certificate renew` I get a very similar error:
```
Error occurs while renewing certificate ([('SSL routines', 'ssl3_read_n', 'unexpected eof while reading')])
```
The debug flag doesn't add any extra information.

This is happening on two different installs (macOS Catalina and Ubuntu 18.04.4), I used the conda package to install. I have the latest openssl version (1.1.1e) on both platforms.

I am wondering if it related to the latest version of openSSL, as there is a similar error reported for the esgf-pyclient (https://github.com/ESGF/esgf-pyclient/issues/55) and I have had the same issue attempting to use that tool. 
I've seen suggestions to downgrade to the previous version of openssl so I will try that, but just wanted to alert you to this issue, in case it isn't just me having done something wrong with my set up or in case anyone has any other fixes or suggestions.

**Comment by YanchunHe** [comment]
My experience is that if you upgrade openssl to 1.1.1.f, it will fix this issue.

But I expect then there will be issues retrieving the certificate, and issues to get globus authentication token...

**Comment by Fehings** [comment]
Thank you Yanchun! Using conda to reinstall openssl gave me a version that worked, so it does run fine now. : )
I am not sure of the git etiquette with this, but as the issue is still there with synda and the openssl 1.1.1e version I am leaving this open for now - if you think this should be closed given the easy fix of just up/down-grading openssl then by all means do close it.

**Comment by YanchunHe** [comment]
Glad to hear this also works for you! But you can decide if this issue keeps open or not.
But indeed, the conda recipe for synda installation should exclude openssl1.1.1e in future updates.
