### ISSUE TITLE
Move entry_point to setup.py

### ISSUE THREAD

**Issue by zklaus** [Prodiguer/synda#156]
Right now, the entry point, that installs the main synda executable, is defined in the conda recipe.
Instead, it could be defined in `setup.py`. That way, a simple `pip install -e .` could be used to install synda from a cloned repository (given a suitable environment).

@AtefBN, is there a particular reason to do this in the recipe?

**Comment by AtefBN** [comment]
No reason in particular why the entry point is in the recipe file. I will have to test the packaging with entry points in the setup.py and if all is well and no regression is to be found I have no problem going this way.

**Comment by AtefBN** [comment]
Hi again, change is now pushed to master. Entry point is in setup.py instead of the meta.yaml, I have not observed any regressions with the change.
