### ISSUE TITLE
Not sure what is going on here

### ISSUE THREAD

**Issue by RuthPetrie** [Prodiguer/synda#157]
https://github.com/Prodiguer/synda/blob/baad853dbd26bb6e16e3d97c8fd3b9b079b75e12/sdt/bin/sdconfig.py#L163

I installed the latest Synda yesterday and it is running ok, however when I do a `synda install -s <selection-file>` and then say yes, I get a "here" printed to screen for each file installed. I am not sure what is going on with this section as it has added the files and downloaded them fine...

**Comment by AtefBN** [comment]
Hi Ruth, is this issue still current? That print statement was commented out and on my environment running version 3.12 of Synda.

**Comment by RuthPetrie** [comment]
It still appears in the master branch.

**Comment by AtefBN** [comment]
Hi @RuthPetrie should be all good now. Drafted new release. Let me know if any other weird prints pollute the output.
