### ISSUE TITLE
Wget timeout config in source code

### ISSUE THREAD

**Issue by AtefBN** [Prodiguer/synda#160]
wget timeout in daemon mode at the moment is encoded within the source in sdconts (line 150)
This type of configuration needs to be outside in sdt.conf ideally to ensure users can change the behavior without changing the code.

**Comment by hanjunkim0617** [comment]
Hello. My name is Hanjun Kim, who is using the Synda for downloading the large data from ESGF. Thank you for making such nice program. 

During using the function "synda install", I found that some data is not downloaded but stays in the running queue for about 20 minutes before going to error queue. Is there any method to shorten this time? I think this is related to the "wget timeout in daemon mode" so upload the question here.  I'm using Synda version 3.15 with Conda installation.
In addition, I wonder if I change the options in bin/sdget.sh, it affects the downloading by "synda install" or not.

Thank you, 
Hanjun

**Comment by pjournou-ipsl** [comment]
A enhancement in synda version 3.15 allows you to update the timeout value that is passed as an argument when synda calls the wget HTTP client.
This entry is located in the sdt.conf file, in the [download] section. Its name is async_http_timeout.
By default, its value is 120 (that means 120 seconds). The value may be set lower if necessary.

**Comment by hanjunkim0617** [comment]
Thank you for answering! I changed the option.
