### ISSUE TITLE
latest Synda overwrites user settings

### ISSUE THREAD

**Issue by painter1** [Prodiguer/synda#167]
The Synda in the latest master branch overwrites the user's /etc/synda/sdt/credentials.conf and sdt.conf.  In fact, two different places in the code do this!  There is no sensible reason to do this ever, if the files exist at all.

**Comment by pjournou-ipsl** [comment]
By code, Synda overwrites your credentials.conf file only if you execute the init-env sub-command. 
You have an interactive mode to update it with the check-env sub-command (and to prevent mistakes, this user action must be confirmed on the command line).

Synda overwrites your sdt.conf file, only during a check-env action. And the update just concerns paths that depend on ST_HOME environmental variable, probably to ensure the synda configuration coherence. This feature, in its intent, has not been changed recently.

Please, send us a user case if you observe any other behavior.

**Comment by pjournou-ipsl** [comment]
Let us inform you that in the future 3.4 release (2021), synda will take into account the paths, as customized into the sdf.conf file.
Synda will set default values only for the case User let them uncustomized.
