### ISSUE TITLE
Master branch update broke sdnexturl.py

### ISSUE THREAD

**Issue by painter1** [Prodiguer/synda#168]
The Synda in the latest master branch (f0beaec41e944126bee510d6850740bfa2068ede) omits the code in sdnexturl.py which pertains to remove_unsupported_url().  This breaks the url calculation and leads to a hard crash (not a Python exception).

**Comment by pjournou-ipsl** [comment]
Thank you for your message. This bug is now fixed (commit 287d3ea...).

**Comment by painter1** [comment]
Thank you.  That will prevent a crash.  Is there another place which ensures that sdquicksearch.run() will not return useless urls, i.e. OpenDAP or Globus?

**Comment by pjournou-ipsl** [comment]
We removed the globus and opendap features, so we can ensure that sdquicksearch.run() will not return useless urls.

Last news about synda : we have encountered some troubles during the deployment of our last synda versions on anaconda platform due, particularly, to the major paradigm change (migration from python 2 to python 3).
We hope the 3.32 latest version will give full satisfaction.

**Comment by painter1** [comment]
That's good news to me - dropping globus and OpenDAP from sdquicksearch.run() simplifies the rest.  I'll close this issue.
