### ISSUE TITLE
synda check-env converts openID to lower case

### ISSUE THREAD

**Issue by clairbarnes** [Prodiguer/synda#177]
Hi,

I think there's a bug in the way synda stores user credentials via `synda check-env`. My openID has been written in lower case, when actually there should be a capital letter in the user ID string. ESGF openIDs are case sensitive, so this causes user identification to fail.

The issue can be easily fixed by the user manually updating `$ST_HOME/conf/credentials.conf`, but this really shouldn't be necessary!

Thanks,

Clair

**Comment by pjournou-ipsl** [comment]
Thank you for your analysis. You're right.

We worked on a new release. The 3.33 delivered today fixes the problem.
