### ISSUE TITLE
Synda doesn't find CORDEX data

### ISSUE THREAD

**Issue by Zeitsperre** [Prodiguer/synda#183]
Synda version: v3.34 (conda)

I've been trying to download CORDEX data using the newest available Synda/sdt, and it seems to not be finding any CORDEX data at all. 

With a selection file for the following:
```
project=CORDEX
domain=NAM-22,NAM-44
variable=pr,tas,ta,uas,vas,ua,va,huss,hus
frequency=3hr,day
```
I would expect quite a lot of data returned, but I receive `INFO: Nothing to install (0 file found).`

I've reinitialized my environment and my credentials are valid/working. With similar tests for CMIP5 and CMIP6 data everything works as expected.

**Comment by Zeitsperre** [comment]
Attempting the example in the documentation also yields no results:
```
$ synda search atmos mon tasmin CMIP5 CNRM-CM5 timeslice=197001-198512 -f
INFO: 'atmos' value has been associated with 'realm' facet.
INFO: 'mon' value has been associated with 'frequency' facet.
INFO: 'tasmin' value has been associated with 'variable' facet.
INFO: 'CNRM-CM5' value has been associated with 'driving_model' facet.
File not found
```

**Comment by pjournou-ipsl** [comment]
Some improper old default settings seem to be the cause of the problem.

I can suggest you to add a line replica=false into your selection file. You can then test this new configuration.

If the result is correct, you can also remove (or update) the line replica=true (by replica=false) into your $HOME/conf/default/default.txt, to avoid such kind of problems in the future.

**Comment by Zeitsperre** [comment]
Hi @pjournou-ipsl, it turns that was exactly the issue/fix needed to solve my problem. Merci énormément!
