### ISSUE TITLE
Where can I find up to date documentation?

### ISSUE THREAD

**Issue by bouweandela** [Prodiguer/synda#188]
Currently, the documentation on http://prodiguer.github.io/synda/index.html says that it is for version 3.0 of Synda in the title in the top left corner. Clicking on the changelog shows entries up to version 3.8. However, from looking at this repository, I can see that you are now at version 3.35. Where can I find the documentation for the latest version?

**Comment by bouweandela** [comment]
In particular, I would be interested in the selection file format. Is the documentation up to date? Are there any changes planned to the format?

**Comment by pjournou-ipsl** [comment]
You're right. We are sorry for the inconveniences.

Let me say that we are working on the synda documentation. A new version will be soon available.

However, the doc part concerning the selection file format is up to date. 

As far as I know, no big change is planned except that the grid ftp protocol will be soon deprecated.

**Comment by AtefBN** [comment]
The synda documentation has been reviewed and updated. 
I will be marking this issue as closed but feel free to open it up again in case of further issues.
Cheers

**Comment by bouweandela** [comment]
Thanks!
