### ISSUE TITLE
Synda reports lots of failed checksums

### ISSUE THREAD

**Issue by Zeitsperre** [Prodiguer/synda#192]
I've been trying to download a fairly extensive selection of CORDEX data, and I am noticing that on average more than 90% of downloads are failing due to a mismatched checksum. The data is being downloaded into a ZFS-formatted disk with on-the-fly compression, but I don't imagine that would have an impact on the SHA sums. The internet connection speed is more than adequate.

These numbers seem oddly high, and it has me wondering if there are any options I should consider looking into. I'm not comfortable relaxing the checksum verification as this data is being used in production. Is there an issue with reported file checksums for CORDEX data on ESGF ?

An example output:

`2021-10-08 16:40:05,042 INFO SDDMDEFA-102 Transfer failed (sdget_status=0,sdget_error_msg=,error_msg='File corruption detected: local checksum doesn't match remote checksum',file_id=22398,status=error,local_path=/{me}/{folders}/synda/downloads/cordex/output/NAM-22/OURANOS/MPI-M-MPI-ESM-LR/rcp85/r1i1p1/CRCM5/v1/day/tas/v20181107/tas_NAM-22_MPI-M-MPI-ESM-LR_rcp85_r1i1p1_OURANOS-CRCM5_v1_day_20860101-20901231.nc,url=http://cordexesg.dmi.dk/thredds/fileServer/cordex_general/CORDEX/output/NAM-22/OURANOS/MPI-M-MPI-ESM-LR/rcp85/r1i1p1/OURANOS-CRCM5/v1/day/tas/v20181107/tas_NAM-22_MPI-M-MPI-ESM-LR_rcp85_r1i1p1_OURANOS-CRCM5_v1_day_20860101-20901231.nc)`

And a queue readout: 

```
status      count  size
done           89  31.6 GB
error        1134  419.8 GB
running         8  2.8 GB
waiting     48433  8.8 TB
```

Thanks again!

**Comment by pjournou-ipsl** [comment]
From synda side, the checksum is calculated only when the size of the file is the same as expected.

So, the team would like to add this new item to the analysis, about your sentence :
"The data is being downloaded into a ZFS-formatted disk with on-the-fly compression, but I don't imagine that would have an impact on the SHA sums."

The team expects that the ZFS-formatted disk may explain the errors encountered during the checksum control step.
