### ISSUE TITLE
Unable to change setting of data_path in Synda

### ISSUE THREAD

**Issue by xlevine** [Prodiguer/synda#193]
Hello,

I am in the process of setting up Synda and I am encountering an issue: while I can easily install data in the data folder setup by default ( $ST_HOME/.synda/data/ ), I am unable to change this setting to have the data installed in another folder. 
I have tried to change this in $ST_HOME/.synda/conf/std.conf by changing the data_path option (my ST_HOME=/cluster/projects/nn8002k/.synda ):

----- In std.conf: 

[daemon]
user =
group =

[module]
download = true

[log]
verbosity_level = info
scheduler_profiling = 0

[core]
security_dir_mode = tmpuid
metadata_server_type = esgf_search_api
selection_path = /cluster/projects/nn8002k/.synda/selection
default_path = /cluster/projects/nn8002k/.synda/conf/default
**data_path = /trd-project4/NS8002K/xale/ESGF**
db_path = /cluster/projects/nn8002k/.synda/db
sandbox_path = /cluster/projects/nn8002k/.synda/sandbox

.....
Whatever path I set up for **data_path** is not taken into account by Synda; instead the default data path ( .synda/data ) is still used by _synda install_. Is there a way to change data folder path to be different than its default setting, and if so how to do it? 

Many thanks for your help, any guidance would be much appreciated.

Best regards,
Xavier.

**Comment by pjournou-ipsl** [comment]
Let inform you that in the future 3.4 release (2021), synda will take into account the paths, as customized into the sdf.conf file.

**Comment by xlevine** [comment]
Excellent news, thank you for keeping me posted!
