### ISSUE TITLE
synda daemon succefully started but download does not work

### ISSUE THREAD

**Issue by dlebars** [Prodiguer/synda#194]
I am using a new synda install with conda on Fedora 34, Python 3.8.12 and synda 3.35

Unfortunately downloading doesn't work.

When starting the daemon I have this message in .synda/log/transfer.log:

> 2021-11-23 14:12:47,789 INFO SDDAEMON-001 Daemon starting ...
> INFO: Connected to /usr/people/bars/.synda/db/sdt.db
> 2021-11-23 14:12:47,794 INFO SDTSCHED-533 Connected to /usr/people/bars/.synda/db/sdt.db
> 2021-11-23 14:12:47,797 INFO SDTSCHED-993 Starting watchdog..
> 2021-11-23 14:12:47,826 INFO SDFILDAO-200 get_files time is 0.024665, search select * from file where status=:status ORDER BY priority DESC, checksum  with {'status': 'running'}
> 2021-11-23 14:12:55,536 INFO SDMYPROX-002 Renew certificate..
> 2021-11-23 14:15:06,536 ERROR SYDLOGON-012 Error occured while retrieving certificate from myproxy server ([Errno 110] Connection timed out)
> Daemon successfully started

I checked my credentials and they work, I can log in on the ESGF website directly so this does not seem to be the problem.

Running 
> synda certificate renew -x

returns:

> Error occurs while renewing certificate ([Errno 110] Connection timed out)

Any idea what is happening?

**Comment by plesager** [comment]
Same issue here, in the same domain. Our workstations have changed domain name. From `knmi.nl` it became `dynamic.knmi.nl`. I wonder if the ESGF is not letting us in somehow.

**Comment by AtefBN** [comment]
Hmm this sounds like an issue external to the synda software itself, will have to carry on tests in our test deployment and see if I can replicate this behavior and maybe find the root reason. 
I agree that this could benefit from a slightly more verbose error message.

**Comment by dlebars** [comment]
The problem was indeed external to synda. It was due to firewall rules on our side.
The issue is actually described on the ESGF FAQ here:
https://esgf.github.io/esgf-user-support/faq.html#network-issues
