### ISSUE TITLE
synda search <timeslice> returns no result 

### ISSUE THREAD

**Issue by ghost** [Prodiguer/synda#41]
```
$ synda search rcp85 20050101-21001231 3hr
Dataset not found

http://esgf-data.dkrz.de/esg-search/search?fields=instance_id,id,type,data_node,variable&project=CMIP5&time_frequency=3hr&experiment=rcp85&limit=100&distrib=true&query=20050101-21001231&type=Dataset&format=application%2Fsolr%2Bxml&offset=0
```

**Comment by jripsl** [comment]
timeslice should be splitted and set submitted using 'start' and 'from' facets

    synda search rcp85 3hr start=2005-01-01T00:00:00Z end=2100-12-31T23:59:59Z

**Comment by pjournou-ipsl** [comment]
`usage: synda search [-h] [-s SELECTION_FILE] [-n] [-z] [-l LIMIT] [-r]
                    [-a | -d | -f | -v]
                    [parameter [parameter ...]]

positional arguments:
  parameter             search parameters. Format is name=value1,value2.. ...
                        Most of the time, parameter name can be omitted.

optional arguments:
  -h, --help            show this help message and exit
  -s SELECTION_FILE, --selection_file SELECTION_FILE
  -n, --no_default      prevent loading default value
  -z, --dry_run
  -l LIMIT, --limit LIMIT
                        Set the total number of returned results. By default,
                        returns the first 100 records matching the given
                        constraints. Limit can be also be changed through the
                        keyword parameters limit=. The system imposes a
                        maximum value of limit <= 10,000.
  -r, --replica         show replica
  -a, --aggregation
  -d, --dataset
  -f, --file
  -v, --variable
`
Try : synda search experiment=rcp85 frequency=3hr start=2005-01-01T00:00:00Z end=2100-12-31T23:59:59Z
