### ISSUE TITLE
users may need to edit `ESGF_OPENID_REXP` in `lib/sd/sdopenid.py`

### ISSUE THREAD

**Issue by papplegate** [Prodiguer/synda#44]
Hi, 

The regular expression contained in `ESGF_OPENID_REXP` in `lib/sd/sdopenid.py` doesn't seem to accommodate (at least some) OpenIDs.  I suggest that the documentation be updated to indicate that users may have to change this regular expression.  

I recently created a new user account on the Earth System that gave me the OpenID `https://www.earthsystemgrid.org/myopenid/my_user_name`.  

When trying the test command `synda get GeoMIP IPSL Tas mon`, I got error `SDOPENID-002`.  Searching with `grep` suggested that this error message came from `lib/sd/sdopenid.py`.  

I modified the line containing `ESGF_OPENID_REXP` from 

ESGF_OPENID_REXP = r'https://.*/esgf-idp/openid/(.*)'

to 

ESGF_OPENID_REXP = r'https://www.earthsystemgrid.org/myopenid/(.*)'

which seemed to give better results.

**Comment by jripsl** [comment]
Hi,

Indeed, the regex can be more generic regarding url path.

In fact, as username cannot contain slash character, the regex can be changed for 

`
r'https://.*/([^/]+)'
`

(i.e. the username is always at the end)

Fixed in 3.5-devel. 

Thanks for your feedback.

**Comment by papplegate** [comment]
Thanks very much for this change.  

It might also be useful to update the documentation and/or the error messages in `lib/sd/sdopenid.py` to show that OpenIDs from earthsystemgrid.org *do not work* for downloading data from the Earth System Grid.  I found this out by e-mailing esgf-user@lists.llnl.gov.

**Comment by jripsl** [comment]
This is misleading indeed. 
I added a warning if a non-working openid is detected.
Thanks
