### ISSUE TITLE
"Warning: cannot retrieve parameters from ESGF" msg during install

### ISSUE THREAD

**Issue by jripsl** [Prodiguer/synda#53]

**Comment by jripsl** [comment]
Fixed (replaced "synda cache init" with "synda update").

**Comment by tobstac** [comment]
I am getting the same error message during installation as well as when trying to access ESGF data
[synda_error.txt](https://github.com/Prodiguer/synda/files/2926996/synda_error.txt)
using synda 3.8. Unfortunately, I have no clue how to apply the fix mentioned above or whether it is still valid. Is there any additional information I could provide to help fix this issue?

**Comment by tobstac** [comment]
Something more to add: I just run a `synda update` on a previously working synda installation. The update failed with the same error following the sdcache.run(reload=True,...) call. Now, this installation runs into the same problem as the new one.
