### ISSUE TITLE
If you default to gridftp and a endpoint is not working then fallback to http.

### ISSUE THREAD

**Issue by SebastienDenvil** [Prodiguer/synda#57]
1. If you default to gridftp but the endpoint is not working properly synda will fallback to http.

**Comment by SebastienDenvil** [comment]
Otherwise because there are too much broken gridftp deployment you will suffer a hard time figuring out the next step of your replication process.

**Comment by jripsl** [comment]
Added in 3.5.

https://github.com/Prodiguer/synda/blob/master/sdt/doc/configuration_parameter_reference.md#downloadhttp_fallback
