### ISSUE TITLE
Synda installer not finding st_root

### ISSUE THREAD

**Issue by Gringo5000** [Prodiguer/synda#59]
I've been trying to either install the globustransfer module or even upgrade my 3.4 install and the installer consistently gives me a message saying "activate not found" with no messages in the install.log
```
[root@aimsdtn6:~]# ./synda_install.sh -u 
Installation in progress...
To see installation details, open a new terminal and run the command 'tail -f /root/install.log'
INSTALL-ERR002 - activate not found
```
If I provide the -t option with the standard path, it then complains about other issues:
```
./synda_install.sh -t /usr/share/python/synda -u 
Installation in progress...
To see installation details, open a new terminal and run the command 'tail -f /root/install.log'
INSTALL-ERR404 - Incorrect new version
[root@aimsdtn6:~]# tail install.log 
[root@aimsdtn6:~]# ./synda_install.sh -t /usr/share/python/synda -u -d 3.6
Installation in progress...
To see installation details, open a new terminal and run the command 'tail -f /root/install.log'
INSTALL-ERR404 - Incorrect new version
```
With the latter error, I do see the following one line in the install.log:
```
[root@aimsdtn6:~]# cat install.log 
cat: /usr/share/python/synda/sdt/lib/sd/sdapp.py: No such file or directory
```

My previous install is 3.4, using an RPM. During my attempts to install the globusonline module, I ran the following as well and the log shows it apparently installing 3.6, yet at the end, synda -V still shows 3.4.
```
[root@aimsdtn6:~]# bash synda_install.sh -t /usr/share/python/synda/sdt sdt globustransfer
Installation in progress...
To see installation details, open a new terminal and run the command 'tail -f /root/install.log'
Installation complete.
```

**Comment by Gringo5000** [comment]
I can see the path to activate is relative to st_root but that variable doesn't seem to get populated, even when using -t or setting st_root and ST_HOME in the shell.

**Comment by Gringo5000** [comment]
I had renamed install.sh to synda_install.sh to be more descriptive. I just noticed if I rename it back to install.sh it tends to work better (though still appears to crash before the end of the install):
```
Collecting pillow>=2.4.0 (from reportlab)
  Using cached Pillow-4.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/root/pip-build-525vF6/pillow/setup.py", line 138
        required = {'jpeg', 'zlib'}
                          ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/root/pip-build-525vF6/pillow/
```

**Comment by jripsl** [comment]
Regarding the first two comments, the problem is that "install.sh" script cannot be used to upgrade an RPM based installation. This script is only for "source installation".
The upgrade guide for RPM installation is available here:
https://github.com/Prodiguer/synda/blob/master/sdt/doc/upgrade_guide.md

Regarding the third comment, this is a bug caused by an non-backward compatible change in an external library. It should only affect 3.6 version installed from source (RPM 3.6 and DEB 3.6 should not be affected). 
It has been fixed in 3.7.
It can be fixed by downgrading the pypi pillow package

    pip install pillow==3.4.2

**Comment by Gringo5000** [comment]
Jerome,
Thanks for the comments. I thought the install.sh might only be for the source install; however, the procedure for installing the globustransfer module seemed to be through the use of install.sh, thus the reason for my attempts. At any rate, I ended up upgrading everything to 3.6 via RPM.

**Comment by jripsl** [comment]
Yes I confirm *globustransfer* module it is only available for source installation at the moment.
