### ISSUE TITLE
Project specific drs_path_template 

### ISSUE THREAD

**Issue by soay** [Prodiguer/synda#6]
Can we have a project specific drs_path_template rather than building the drs from dataset_id?
Maybe we could add project specific sections to the config file and read the drs_path_template from it? That would be similar to ESGF's esg.ini, but unlike esg.ini specifying the drs_path_template should be optional, i.e. use the default (dataset_id) if it's not specified. 

E.g. for CORDEX:
drs_path_template=cordex/%(product)s/%(domain)s/%(institute)s/%(driving_model)s/%(experiment)s/%(ensemble)s/%(institute)s-%(rcm_name)s/%(rcm_version)

**Comment by jripsl** [comment]
Feature added in todo list.

**Comment by jripsl** [comment]
Feature added in 3.3.

To enable it, 'local_path_format' must be set  to 'custom' and 'local_path_drs_template' must contain the new drs.

Both variable must be set in the selection file.

e.g. 
```
local_path_format=custom
local_path_drs_template=cordex/%(product)s/%(domain)s/%(institute)s/%(driving_model)s/%(experiment)s/%(ensemble)s/%(institute)s-%(rcm_name)s/%(rcm_version)s/%(time_freq
uency)s/%(variable)s/%(dataset_version)s
```
