### ISSUE TITLE
Need a way to specify -nodcau for gridftp transfers

### ISSUE THREAD

**Issue by cmharr** [Prodiguer/synda#60]
We have found when using gridftp as the transfer protocol for synda that we need to specify the -nodecau option to bypass certificate problems. For the moment, we've manually edited the GRIDFTP_OPT variable in /usr/share/python/synda/sdt/bin/sdgetg.sh to include that option. Is there a better way to supply that option, or if not, can an option be added to supply gridftp options?

**Comment by jripsl** [comment]
Good idea. "gridftp_opt" parameter has been added in "sdt.conf". It will be available in the next release (3.9). Setting this parameter will prevent the need to edit " /usr/share/python/synda/sdt/bin/sdgetg.sh".
