### ISSUE TITLE
synda user in daemon mode

### ISSUE THREAD

**Issue by glevava** [Prodiguer/synda#62]
With a normal user, synda daemons are run with the user login:

```
glipsl   26175     1 21 11:22 ?        Sl     0:01 /usr/share/python/synda/sdt/bin/python /usr/share/python/synda/sdt/bin/sddaemon.py start
glipsl   26186     1  0 11:22 ?        Sl     0:00 /usr/share/python/synda/sdp/bin/python /usr/share/python/synda/sdp/bin/spdaemon.py start
```

Several users can run several daemon plugged on the same database...

A multi-user context should run synda daemon under the same "no-login" account, called "synda" for instance.
Consequently, the normal user can only run and interact with the same daemon.

Another practice : root could the only user to start/stop synda services.

**Comment by pjournou-ipsl** [comment]
In the future 3.4 release, the features based on the daemon will be deprecated. A new feature for asynchronous downloads will be implemented.
