### ISSUE TITLE
ubuntu 16

### ISSUE THREAD

**Issue by matthiasdemuzere** [Prodiguer/synda#64]
Hi,

I am working on ubuntu 16.04 LST, but noticed that this distro is not listed in the .deb packages?
Would it be possible to make this one also available?

Thanks.
Matthias

**Comment by jripsl** [comment]
Hi,
Ubuntu 16 package for Synda 3.8 has been added.
https://github.com/Prodiguer/synda/blob/master/sdt/doc/deb_install.md
Regards
Jerome

**Comment by matthiasdemuzere** [comment]
Great. Thanks.
