### ISSUE TITLE
change path to worker.log [Issue renamed from: in worker, allow configuration of logging level]

### ISSUE THREAD

**Issue by alaniwi** [Prodiguer/synda#65]
In https://github.com/Prodiguer/synda/blob/master/sdw/bin/worker the `logging` library is used, but the level is never set, meaning that the default level `logging.WARN` is used. Therefore, various useful messages, including the standard output of any shell scripts run, are lost because they are below this threshold.

Please add code to read in a logging level from the config file (if one is specified) and apply that. I would suggest logging via a logger returned by `logging.getLogger` and using its `setLevel` method, but alternatively it is possible to use `logging.basicConfig` to change the logging level of the root logger:
```
>>> import logging
>>> logging.basicConfig(level = logging.DEBUG)
>>> logging.debug("hello")
DEBUG:root:hello
```
(Note that `logging.basicConfig` can only be run once in the python session. Any subsequent calls are ignored.)

The level can also be specified as a string (e.g. `"DEBUG"`), but alternatively, `logging.getLevelName()` will do the lookup (in either direction - despite the method name, it can also convert the level name to its numerical value).

**Comment by jripsl** [comment]
I added an option to set the log level.

By the way, this script was already set to DEBUG by default, by calling "logging.basicConfig".
I guess you are using another version (i.e. different versions of this script exist).

**Comment by alaniwi** [comment]
Sorry, Jérôme, you are correct. We were not seeing the log messages, so I assumed that the logging level was incorrect. It turns out that we were looking in the incorrect file.

We did an installation from source, using:
 
```
wget --no-check-certificate https://raw.githubusercontent.com/Prodiguer/synda/master/sdc/install.sh
bash install.sh -t <directory>
bash install.sh -t <directory> postprocessing
```
This creates an `sdp` directory, although no `sdw` directory - and the worker is called `sdp/bin/synda_wo`. It also creates a log directory `sdp/log/`. (We installed `sdt` in case it includes any software components that are required by sdp, but we are not running sdt on this host, only sdp.)

When we look in the `sdp/log/` directory, we find only `daemon.log` and `stacktrace.log`. So I assumed that the messages should appear in `daemon.log` if the log level permits. Now I have looked at the code again, and see that in fact it is creating `/tmp/worker.log`. I also see that this file in fact contains the script output which seemed to have been lost.

Please could you change the logic regarding the directory path for `worker.log`, so that after a source installation it is created in the same directory as `daemon.log` and `stacktrace.log`. If it was there instead of `/tmp` then we would have found it. (Also if it is in `/tmp` then it may get deleted.) Thank you.

**Comment by jripsl** [comment]
To have log files be in the same directory as daemon.log and stacktrace.log, you need to set "SP_HOME" env. var.

    export SP_HOME=$HOME/sdp

    https://github.com/Prodiguer/synda/blob/master/sdp/doc/src_install.md

Log files are stored in /tmp for when the "worker" script run on a different machine than sdp.

(the "SP_HOME" variable is used to distinguish between the two mode)

Log files location management is a bit tricky because of the different mode of installation/execution, but when the script starts, it prints the log destination folder (on stdout) to inform users where the log files are stored.
