### ISSUE TITLE
limits of sqlite?

### ISSUE THREAD

**Issue by cehbrecht** [Prodiguer/synda#69]
I just started to use synda ... have no experience here ... just guessing :)

synda uses the sqlite database. I have noticed that it protocols each downloaded file in the sqlite database. I would guess that if you keep only one instance of synda to replicate cmip6 with millions of files it might slow down ... just a guess, not sure about it.

You don't use [SQLAlchemy](http://www.sqlalchemy.org/)? If you would do so, one would have the option to use a different database like postgres. 

Or maybe using some kind of key-value store?

**Comment by SebastienDenvil** [comment]
We might decide to optimize this but haven't had any performance issue up to now. We replicated CMIP5 and CORDEX.

sqlite limits seem hard to reach.
https://sqlite.org/limits.html

**Comment by pjournou-ipsl** [comment]
We have this implementation in our TODO list (probably available in 2022)
