### ISSUE TITLE
synda install -s selection.txt  reports 0 files found

### ISSUE THREAD

**Issue by laubblatt** [Prodiguer/synda#7]
Hi,
I want to download a batch of CMIP5 model runs using the template file.
This worked great two weeks ago. 
Now I need more output, but for any selection.txt (also the example files in selection/sample/) I do get the following output:
```
synda install -s selection.txt 
Nothing to install (0 file found).

```
I use version 3.2 installed locally on Ubuntu 12.04 from sources.

Any idea?
Thanks,
Maik
--

Here is my selection file: 

project=CMIP5
model=ACCESS1.0 ACCESS1.3 BCC-CSM1.1 BCC-CSM1.1(m) CCSM4 CNRM-CM5 CNRM-CM5-2 CanESM2 GFDL-CM3 GFDL-ESM2G GFDL-ESM2M GISS-E2-H GISS-E2-R HadGEM2-ES INM-CM4 IPSL-CM5A-LR IPSL-CM5A-MR IPSL-CM5B-LR MIROC-ESM MIROC5 MPI-ESM-LR MPI-ESM-MR MPI-ESM-P MRI-CGCM3 MRI-ESM1 NorESM1-M
experiment=piControl
ensemble=r1i1p1
variable[atmos][mon]=hfls hfss rsds rsus rlds rlus rlut prc ts tas

**Comment by jripsl** [comment]
Can you retry after setting parameters below in /etc/synda/sdt/sdt.conf file 

check_parameter=0
indexes=esgf-data.dkrz.de
default_index=esgf-data.dkrz.de

Thanks

**Comment by laubblatt** [comment]
Thanks for your fast reply. 
Changing the index did the trick!
indexes=esgf-data.dkrz.de
default_index=esgf-data.dkrz.de

I had pmnl.... before.

Only thing which is remaining is that when using the long list of models I get this error:

```
Entity: line 434610: error: xmlSAX2Characters: huge text node: out of memory
      <str>http://esgf-data1.ceda.ac.uk/thredds/fileServer/esg_dataroot/cmip5/ou
```
When using just two models all went smoothly!
