### ISSUE TITLE
synda remove kills daemon

### ISSUE THREAD

**Issue by painter1** [Prodiguer/synda#71]
When I run "synda remove -s ...." on an active job, the daemon is quietly killed.  I have to manually restart it.

**Comment by SebastienDenvil** [comment]
May be a bug or a wrong diagnostic. Will try to reproduce.

**Comment by painter1** [comment]
No relevant error messages appear in those files.  There is no file /tmp/sdt_*; could it be in another directory?

**Comment by pjournou-ipsl** [comment]
In the future 3.4 release, the features based on the daemon will be deprecated. A new feature for asynchronous downloads will be implemented.
