### ISSUE TITLE
selection files are critical

### ISSUE THREAD

**Issue by painter1** [Prodiguer/synda#76]
Synda usage is closely tied to selection files.  Generally this is helpful; but problems can crop if the user edits or deletes the file.

For example, what if the user starts a download job, then realizes that he made a mistake in creating the selection file?  He might edit it substantially, and then forget what changes he had made.  At that point, he can't kill the download with a "synda remove -s ..." because the job's selection file no longer exists!

I don't have a final solution in mind, but this is a real problem which we have to solve.  One crude approach which might work would involve a system log or archive of selection files which had been submitted to "synda install -s ...".

**Comment by glevava** [comment]
`synda history` provides the journal of the selection files installed with their checksums at the installation time. It can be used to highlight two selection files installed with the same file name but different contents, which should be definitely avoid I agree.

Datasets can also be removed using `synda remove <dataset_id>` to get a finer removal according to a selection file modification.
