### ISSUE TITLE
limit on install's search

### ISSUE THREAD

**Issue by painter1** [Prodiguer/synda#78]
When you run "synda install -s ...", it does a search for the files specified in your selection file.  The search url includes '&limit=9000'.  9000 files is plenty of files for a scientist-user, but this makes Synda impossible for production-scale replication - that is, building a large archive as I do.  Any limit will kill attempts at large scale replication.

My short-term patch is to change sdtypes.Request.get_limit_filter() to always return "".
Synda should be changed so that an optional setting in sdt.conf will cause get_limit_filter() to return ""; that is, no limit in the url.

**Comment by SebastienDenvil** [comment]
We do production scale replication to build a large archive since ESGF inception with synda. This has never been a limit and this is because synda will use the pagination until we reach the end of the search result for a single search API query.

**Comment by painter1** [comment]
When I run Synda, pagination is on but does not help.  It could be that the real problem is with the search node.  When the number of files matching the search is more than the limit, then the search node returns "numFound:0" and it does not list any files.

**Comment by SebastienDenvil** [comment]
it might well be indeed. We need to check with Luca.

**Comment by painter1** [comment]
Luca said this problem was a consequence of timeouts when the index server was asked to list a very large number of files.  I tried setting SEARCH_API_CHUNKSIZE to 100 in sdconst.py.  This seems to have fixed the problem, although I will have to check more carefully later.  With the smaller value of SEARCH_API_CHUNKSIZE, pagination is working as it should.

I recommend that SEARCH_API_CHUNKSIZE be set to a smaller number (it is presently 9000).  There may be value in making it settable in sdt.conf, but probably not.

**Comment by painter1** [comment]
I can confirm that a smaller value of SEARCH_API_CHUNKSIZE will solve the problem.
