### ISSUE TITLE
dataset name in selection file

### ISSUE THREAD

**Issue by painter1** [Prodiguer/synda#80]
Often I have to work with a list of dataset names which we need.  We want exactly those datasets, and no more.  Therefore I would like to provide a list of dataset names in the selection file, e.g.
```
 cmip5.output1.FIO.FIO-ESM.historical.mon.atmos.Amon.r3i1p1
 cmip5.output1.ICHEC.EC-EARTH.historical.mon.atmos.Amon.r5i1p1
 cmip5.output1.MRI.MRI-CGCM3.historical.mon.atmos.Amon.r1i1p1
 cmip5.output1.MRI.MRI-CGCM3.historical.mon.atmos.Amon.r2i1p1
 cmip5.output1.MRI.MRI-CGCM3.historical.mon.atmos.Amon.r3i1p1
 cmip5.output1.MRI.MRI-CGCM3.historical.mon.atmos.Amon.r4i1p2
 cmip5.output1.MRI.MRI-CGCM3.historical.mon.atmos.Amon.r5i1p2
 cmip5.output1.MRI.MRI-ESM1.historical.mon.atmos.Amon.r1i1p1
 cmip5.output1.NOAA-GFDL.GFDL-CM2p1.historical.mon.atmos.Amon.r10i1p1
 cmip5.output1.NOAA-GFDL.GFDL-CM2p1.historical.mon.atmos.Amon.r1i1p1
 cmip5.output1.NOAA-GFDL.GFDL-CM2p1.historical.mon.atmos.Amon.r4i1p1
 cmip5.output1.NOAA-GFDL.GFDL-CM3.historical.mon.atmos.Amon.r4i1p1
```
The idea is that a single selection file, and a single "synda install" command will install all these datasets, and no more.  With the present selection file format, I needed six selection files to get exactly this list of datasets.

This feature would be especially useful when a script generates the selection files.

**Comment by pjournou-ipsl** [comment]
Today, the only solution we can give you is to create a single `selection file` that contains the list of the ids of the datasets you want to install. 

An example with two of them :
`dataset_id="cmip5.output1.ICHEC.EC-EARTH.historical.mon.atmos.Amon.r5i1p1.v20171115|esgf.ichec.ie"
 dataset_id="cmip5.output1.MRI.MRI-CGCM3.historical.mon.atmos.Amon.r1i1p1.v20120701|esgf-data1.diasjp.net"`

Please see issue #88 for further details.
