### ISSUE TITLE
"security_dir_mode" doesn't work properly in daemon mode

### ISSUE THREAD

**Issue by glevava** [Prodiguer/synda#85]
https://github.com/Prodiguer/synda/blob/c3710ef2549ca4c31d987667fcb3011c4f1350b3/sdt/bin/sdconfig.py#L200

When daemon takes different identity, `os.getuid()` in `sdconfig.py` always returns the uid who started the service because `sdconfig.py` is imported in `sdtiaction.py` before running the daemon.

**Comment by pjournou-ipsl** [comment]
In the future 3.4 release (end 2021), the features based on the daemon will be deprecated. A new feature for asynchronous downloads will be implemented instead.

Moreover, know that a class Config has been created and can be instantiated whenever it is useful. Consequently, the case described in this issue can now be avoided.
