### ISSUE TITLE
Download only a certain version of a dataset

### ISSUE THREAD

**Issue by laubblatt** [Prodiguer/synda#88]
Hi,
I am working with CMIP5 model output. Some models have output of different versions, but not complete for all variables. For example:
`synda version cmip5.output1.MOHC.HadGEM2-ES.piControl.mon.atmos.Amon.r1i1p1.v20130114`

How can I use synda to download a specific version / latest version of the data only? I would prefer the `synda install -s template.txt` style.  

I appreciate any suggestions!
Maik

**Comment by pjournou-ipsl** [comment]
We are sorry, but today, there is a no real solution. 
The only way, when it is possible, is to search for the `id` of the dataset version and add the parameter `dataset_id` and its value into the `template.txt.` 
I started a discussion with the team to see if we can offer a better solution in the future. But keep in mind that the solution is in fact really dependent of the esgf search api design.
