### ISSUE TITLE
can't get only latest version

### ISSUE THREAD

**Issue by painter1** [Prodiguer/synda#89]
The dataset cmip5.output1.CSIRO-QCCCE.CSIRO-Mk3-6-0.amip.mon.land.Lmon.r1i1p1 has two versions, v1 and v20110518.  v20110518 is the latest version.   With the following selection file, 
"synda install -s ..." wants to download _both_ versions.
It is very rare for anyone to want both versions, especially when "latest=true" is specified.  Of course, the two version numbers were constructed differently.  Still, in my extensive experience with CMIP5, it always works to choose the numerically greater version.

```
# cmip5.output1.CSIRO-QCCCE.CSIRO-Mk3-6-0.amip.mon.land.Lmon.r1i1p1
project=CMIP5
product=output1
institute=CSIRO-QCCCE
model=CSIRO-Mk3-6-0
experiment=amip
time_frequency=mon
realm=land
cmor_table=Lmon
ensemble=r1i1p1
latest=true
```

**Comment by hot007** [comment]
Note that CSIRO-Mk3-6-0 did an odd thing of only publishing *changed* variables with new version numbers, so 'latest' for variable A might be a different version to 'latest' for variable B for that model. It's not great, but may explain this behaviour. Check that when you choose the higher numerical version you do actually get all expected vars....

**Comment by senesis** [comment]
From the data producer point of view, and according to CMIP6 rules, it is not odd to avoid duplicating published data for the non-changed variables, even if it complicates a bit the handling by data consumers

**Comment by hot007** [comment]
At least in CMIP6 the 'dataset' is defined at variable level not experiment, the model in question is CMIP5 so it means that what looks like the same dataset may  contain different variables. But you're right, the thinking makes sense, it just makes data handling difficult for users in CMIP5.

**Comment by pjournou-ipsl** [comment]
Today, the only solution we can give you is to add into your `selection file` the id of the dataset you want to install.

For instance, if you want to install the files of the latest dataset (version : 20110518), add the following line :
dataset_id="cmip5.output1.CSIRO-QCCCE.CSIRO-Mk3-6-0.amip.mon.land.Lmon.r1i1p1.v20110518|esgf.nci.org.au"

Please see issues #80 and 88 for further details.
