### ISSUE TITLE
HTTP download fails due to hardcoded TLS 1.0 protocol

### ISSUE THREAD

**Issue by chrisacbr** [Prodiguer/synda#92]
The `sdget.sh` script is hardcoded to use TLS 1.0:
```
TLS_ONLY=" --secure-protocol=TLSv1 "
```

This is problematic if the target server only supports TLS 1.1 or higher.  For example:
```
$ synda get -v -f -d /local/synda/sandbox/ http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MIROC/MIROC5/amip/mon/atmos/Amon/r1i1p1/ta/1/ta_Amon_MIROC5_amip_r1i1p1_198901-199812.nc
wget -D /local/synda/sandbox/ta_Amon_MIROC5_amip_r1i1p1_198901-199812.nc -O /local/synda/sandbox/ta_Amon_MIROC5_amip_r1i1p1_198901-199812.nc --timeout=30 --tries=1 --max-redirect=2 -v --certificate=/var/tmp/synda/sdt/8436/.esg/credentials.pem --private-key=/var/tmp/synda/sdt/8436/.esg/credentials.pem --ca-directory=/var/tmp/synda/sdt/8436/.esg/certificates --ca-certificate=/var/tmp/synda/sdt/8436/.esg/credentials.pem --no-check-certificate --secure-protocol=TLSv1 http://aims3.llnl.gov/thredds/fileServer/cmip5_css02_data/cmip5/output1/MIROC/MIROC5/amip/mon/atmos/Amon/r1i1p1/ta/1/ta_Amon_MIROC5_amip_r1i1p1_198901-199812.nc
[snip]
Connecting to aims3.llnl.gov (aims3.llnl.gov)|198.128.245.183|:80... connected.
HTTP request sent, awaiting response... 302 302
[snip]
Connecting to aims3.llnl.gov (aims3.llnl.gov)|198.128.245.183|:443... connected.
OpenSSL: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
Unable to establish SSL connection.
Transfer failed with error 1 (did you subscribe to the required role/group ? (e.g. cmip5_research, cordex_research))
```

I think it would be much better to allow the client to negotiate the highest protocol supported by both ends; ie. just remove the `--secure-protocol` option altogether. Furthermore, the name of the variable seems to imply (perhaps inadvertently) that the intention here is to prevent non-TLS connections. However, that option only controls what protocol is used *when* a secure connection is made; it doesn't prevent the request going over an insecure connection; eg. as shown in the first redirect above.  Also, since `--no-check-certificate` is used, it seems somewhat academic since there is no guarantee that the client isn't connecting to a MITM server anyway.

**Comment by beyerle** [comment]
I vote for remove the `--secure-protocol=TLSv1` option altogether! Otherwise many downloads are failing.

Hotfix:
`sed -i "s|--secure-protocol=TLSv1||" ~/sdt/lib/sd/sdget.sh`

**Comment by Zeitsperre** [comment]
This was enough to solve the issue for me, allowing me to download what I needed without authorization failures.

@painter1 would the maintainers appreciate a PR for me to add this change?

**Comment by AtefBN** [comment]
@Zeitsperre feel free to post a PR with the fix, i'll happily review and merge it yes 👍

**Comment by Zeitsperre** [comment]
I imagine this can be closed. The fix is integrated. :)
