### ISSUE TITLE
http_fallback option in a selection file

### ISSUE THREAD

**Issue by RuthPetrie** [Prodiguer/synda#93]
Would it be reasonable to request including the http_fallback switch in the selection file overwriting the default from the config? This would make testing a lot easier. Consider also perhaps you have a very large transfer but as a default `http_fallback=true` is set in the sdt.conf file you may want to insist on a gridftp transfer but if doing other smaller transfers http fallback is ok but for one selection file you may want it to fail if gridftp fails.

**Comment by pjournou-ipsl** [comment]
For information, in the next 3.4 release (end 2021), the features based on the gridftp protocol will be deprecated. So, Synda will only support the http protocol.
