### ISSUE TITLE
pyOpenSSL package dependency update

### ISSUE THREAD

**Issue by meteorologist15** [Prodiguer/synda#96]
In terms of the install script, the dependency package pyOpenSSL has been updated to version 18.0.0 as of May 16, 2018, and no longer supports Python 2.6. 

https://pypi.org/project/pyOpenSSL/

As the default install of Python is 2.6.6, either pyOpenSSL will need to be downgraded to 17.5.5 or the Python default install will need to be upgraded to Python 2.7.

**Comment by AtefBN** [comment]
As per synda 3.10 release on conda, the support is 2.7 only. I am also working on a python 3 release that should mark synda 4.0 release.
