### ISSUE TITLE
Report daemon status on startup

### ISSUE THREAD

**Issue by RuthPetrie** [Prodiguer/synda#99]
Currently, I'm using a source installation (though I don't see how this would differ from an RPM installation). 

If I do `synda daemon start` or `synda_pp daemon start` I get no report back as to whether the command has been successfully executed or not. I had not really found this to be a problem until I realised that when starting synda_pp it didn't actually start (just config issue now resolved) however it would have been useful for Synda to report `synda_pp successfully` started or `synda_pp failed to start` in the same way as `synda certificate renew` reports status. If not required as default could be done via a verbose option?

**Comment by AtefBN** [comment]
I agree, this is not ideal. Will work it in the future release.

**Comment by AtefBN** [comment]
[Latest commit](https://github.com/Prodiguer/synda/commit/d7cf5dab274bce3a8a4225bf409c8de284ee9f39) sort of takes care of this. Keep in mind, the daemon is designed to detach from the main process (in this case synda and the stdout) and should run independently. So I just added a message that indicates when synda is about to hand over the reins to the daemon context, as well as the path of the log file that the daemon would be using as a stdout. 

I'm afraid if we go further it'd be at the expense of performance. But I'm open to suggestions.
